### ISSUE TITLE
Race condition ? Can't call method [setHeightInPoints] on object, object is null

### ISSUE THREAD

**Issue by scottsteinbeck** [cfsimplicity/lucee-spreadsheet#230]
@cfsimplicity  Here is my code and i should state that it is about 1200 rows, but when i run it on the big queries
`spreadsheet.addRows		( workbook = workbook, data = data[i].query, includeQueryColumnNames=true);`
`spreadsheet.setRowHeight( workbook, 1, 23 ); // Fails on importing large queries to excel sheet`
`spreadsheet.formatRow	( workbook, headerStyles, 1 );`

Stack trace
```
lucee.runtime.exp.ExpressionException: can't call method [setHeightInPoints] on object, object is null
    at lucee.runtime.reflection.Reflector.callMethod(Reflector.java:872)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:829)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at modules.lucee_spreadsheet270.spreadsheet_cfc$cf.udfCalla(/modules/lucee-spreadsheet/Spreadsheet.cfc:1628)
    at modules.lucee_spreadsheet270.spreadsheet_cfc$cf.udfCall(/modules/lucee-spreadsheet/Spreadsheet.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:646)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall2(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc:520)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall1(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc:13)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall1(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc:395)
    at modules_app.site_api.modules_app.v1.handlers.export_reports_cfc$cf$3.udfCall(/modules_app/site_api/modules_app/v1/handlers/export_reports.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
    at lucee.runtime.type.scope.ArgumentImpl.callWithNamedValues(ArgumentImpl.java:494)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
    at coldbox.system.resthandler_cfc$cf.udfCall(/coldbox/system/RestHandler.cfc:64)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:647)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
    at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
    at coldbox.system.web.controller_cfc$cf.udfCall3(/coldbox/system/web/Controller.cfc:925)
    at coldbox.system.web.controller_cfc$cf.udfCall(/coldbox/system/web/Controller.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
    at lucee.runtime.type.scope.UndefinedImpl.callWithNamedValues(UndefinedImpl.java:792)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
    at coldbox.system.web.controller_cfc$cf.udfCall2(/coldbox/system/web/Controller.cfc:643)
    at coldbox.system.web.controller_cfc$cf.udfCall(/coldbox/system/web/Controller.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.callWithNamedValues(UDFImpl.java:207)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:647)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
    at lucee.runtime.ComponentImpl.callWithNamedValues(ComponentImpl.java:1917)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithNamedValues(VariableUtilImpl.java:864)
    at lucee.runtime.PageContextImpl.getFunctionWithNamedValues(PageContextImpl.java:1729)
    at coldbox.system.bootstrap_cfc$cf.udfCall1(/coldbox/system/Bootstrap.cfc:259)
    at coldbox.system.bootstrap_cfc$cf.udfCall(/coldbox/system/Bootstrap.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.type.scope.UndefinedImpl.call(UndefinedImpl.java:779)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at coldbox.system.bootstrap_cfc$cf.udfCall1(/coldbox/system/Bootstrap.cfc:483)
    at coldbox.system.bootstrap_cfc$cf.udfCall(/coldbox/system/Bootstrap.cfc)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:646)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
    at lucee.runtime.util.VariableUtilImpl.callFunctionWithoutNamedValues(VariableUtilImpl.java:785)
    at lucee.runtime.PageContextImpl.getFunction(PageContextImpl.java:1710)
    at application_cfc$cf.udfCall(/Application.cfc:53)
    at lucee.runtime.type.UDFImpl.implementation(UDFImpl.java:106)
    at lucee.runtime.type.UDFImpl._call(UDFImpl.java:344)
    at lucee.runtime.type.UDFImpl.call(UDFImpl.java:217)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:646)
    at lucee.runtime.ComponentImpl._call(ComponentImpl.java:568)
    at lucee.runtime.ComponentImpl.call(ComponentImpl.java:1898)
    at lucee.runtime.listener.ModernAppListener.call(ModernAppListener.java:436)
    at lucee.runtime.listener.ModernAppListener._onRequest(ModernAppListener.java:132)
    at lucee.runtime.listener.MixedAppListener.onRequest(MixedAppListener.java:42)
    at lucee.runtime.PageContextImpl.execute(PageContextImpl.java:2416)
    at lucee.runtime.PageContextImpl._execute(PageContextImpl.java:2406)
    at lucee.runtime.PageContextImpl.executeCFML(PageContextImpl.java:2381)
    at lucee.runtime.engine.Request.exe(Request.java:43)
    at lucee.runtime.engine.CFMLEngineImpl._service(CFMLEngineImpl.java:1170)
    at lucee.runtime.engine.CFMLEngineImpl.serviceCFML(CFMLEngineImpl.java:1116)
    at lucee.loader.engine.CFMLEngineWrapper.serviceCFML(CFMLEngineWrapper.java:97)
    at lucee.loader.servlet.CFMLServlet.service(CFMLServlet.java:51)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:590)
    at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
    at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:47)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:251)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:186)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:227)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:149)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:111)
    at org.cfmlprojects.regexpathinfofilter.RegexPathInfoFilter.doFilter(RegexPathInfoFilter.java:45)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:251)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:186)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:227)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImplSetup(RequestDispatcherImpl.java:149)
    at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:111)
    at org.tuckey.web.filters.urlrewrite.NormalRewrittenUrl.doRewrite(NormalRewrittenUrl.java:215)
    at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:171)
    at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
    at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
    at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:405)
    at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
    at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
    at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
    at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
    at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
    at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
    at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:68)
    at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
    at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
    at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
    at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
    at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
    at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at runwar.Server$1.handleRequest(Server.java:531)
    at io.undertow.servlet.handlers.SendErrorPageHandler.handleRequest(SendErrorPageHandler.java:52)
    at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:269)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:78)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:133)
    at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:130)
    at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
    at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
    at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:249)
    at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:78)
    at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:99)
    at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387)
    at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:841)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2019)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1558)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1449)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by cfsimplicity** [comment]
@scottsteinbeck How are you creating the workbook? I suspect you are using the SXSSF (streaming) format. Unfortunately you can't make changes to SXSSF rows once they've been created. It's a trade-off with the "streaming" aspect which allows memory efficient handling of large sheets.

If you need to alter the row height, then create the workbook as an XLSX.

I do need to make this clearer in the docs.

**Comment by scottsteinbeck** [comment]
Its just the header row so is it possible to set up the height and format of the first column, and then stream content into it after the fact?

**Comment by cfsimplicity** [comment]
I'm going to investigate a workaround that might allow that, but for now I'm afraid once you've created an SXSSF workbook, you can't alter its `row` objects.

**Comment by scottsteinbeck** [comment]
@cfsimplicity No problem, thanks so much for responding to me so quickly! I will just use the XLSX workbook. Let me know if you find anything. 

And I just want to thank you for creating this library, it is by far the easiest, most versatile, and cleanest library I have ever used to make excel documents. You are awesome!

**Comment by cfsimplicity** [comment]
Thanks!

**Comment by scottsteinbeck** [comment]
@cfsimplicity thank you for looking into that! And I appreciate you actually doing performance tests first to make sure it was a viable solution. 

I have no problem giving them the option to wait a bit longer for the pretty version and just have my code switch from Streaming to non-streaming.

**Comment by cfsimplicity** [comment]
@scottsteinbeck Actually I've realized your use case _is_ possible with SXSSF by adding the header row separately and changing it _before_ you add the main data. As there is just one row at that point, it will still be accessible in memory. 
```
workbook = spreadsheet.newStreamingXlsx();
// add the query columns as the header row
spreadsheet.addRow( workbook, data[i].query.ColumnArray() ); 
// format/adjust the header row
spreadsheet.setRowHeight( workbook, 1, 23 ); 
spreadsheet.formatRow ( workbook, headerStyles, 1 );
// add the rest of the query
spreadsheet.addRows ( workbook = workbook, data = data[i].query, includeQueryColumnNames=false);
// now it's no longer possible to change the first row
```

**Comment by scottsteinbeck** [comment]
@cfsimplicity super cool! I will try it out today 👍
